### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by vkats-spbu** [knyazev-e/HomeAssignments#1]
1. Объектные файлы нужно компилировать каждый своей командой
2. Нет цели на очистку проекта

**Comment by AndreyIsakov01** [comment]
Первый пункт все еще нужно исправить, хотя бы в том формате, который был на лекции. Но лучше разобраться в Makefile, который был на первой практике 
<img width="1106" alt="image" src="https://github.com/user-attachments/assets/837b31f7-174f-4366-9740-3c9c20da78b5">
