### ISSUE TITLE
Заголовочный файл

### ISSUE THREAD

**Issue by vkats-spbu** [knyazev-e/HomeAssignments#2]
Добавить include guard

**Comment by AndreyIsakov01** [comment]
Изменить название guard'а 
Например, если путь до заголовочного файла выглядит следующим образом:
`foo/src/bar/baz.h`
то guard к нему выглядит как 
`#ifndef FOO_BAR_BAZ_H_
#define FOO_BAR_BAZ_H_

...

#endif  // FOO_BAR_BAZ_H_`

https://guiquanz.gitbooks.io/google-cc-style-guide/content/ebook/Header_Files.html
